### PR TITLE
Adding row to card overlay displaying the card's set

### PR DESCRIPTION
**Pull request by shaggywalrus**
Addresses feature request #3853. 
- [x] I have read the [Contributing Guidelines](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md#contributing)
- [x] I have already signed the CLA

### CODE REVIEW

**Comment by shaggywalrus** [comment]
Hearthstone overlay is working after several hours of gameplay, switching decks & using wild decks (to test that it works with older sets). However, the set is mostly cut off for the overlay when you hover over a card in HDT itself.

- [ ] Address missing text in overlay for decklists in HDT itself.

**Comment by shaggywalrus** [comment]
> hearthstoneoverlay
> hdtoverlay
> 
> Hearthstone overlay is working after several hours of gameplay, switching decks & using wild decks (to test that it works with older sets). However, the set is mostly cut off when you hover over a card in HDT itself.
> 
> * [x]  Address missing text in overlay for decklists in HDT itself.

@azeier Helped me out here by pointing out that I hadn't defined the new row. I also removed the unnecessary margin attribute.

**Comment by shaggywalrus** [comment]
The display text for the "Display card set" option doesn't work because it hasn't been added to the localization files. @azeier kindly offered to take care of this when merging this PR.

[] Deal with localization of new menu option.

**Comment by azeier** [comment]
Looks good 👍

**Pull request merged**
