### PR TITLE
Spell Counter for Arcane Giant

### PR DESCRIPTION
**Pull request by barefootdeveloper**
Extended the spell counter to work for Arcane Giant as well
This should allow #2767 to be closed.  I also had the thought of reducing the mana cost in the cards list, but I didn't want to be presumptuous

### CODE REVIEW

**Comment by azeier** [comment]
- I don't think this needs it's own config value and selector in the UI. Extending the logic in `WotogCounterHelper` (basically the same way it is now, just without `PlayerArcaneGiantCounter `) and changing the options label from `Show Yogg-Saron counter` to `Show spell counter` should be fine.
- [Please use tabs, not spaces](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md#coding-style).
- There is a new line in `OverlayWindow.Update` for some reason :).

**Comment by barefootdeveloper** [comment]
There you are, I had to change my visual studio settings to keep your tabs, the default is spaces.

**Comment by azeier** [comment]
Very nice :). Fixup those commits into one and we are gtm.

**Comment by barefootdeveloper** [comment]
Closing for new pull request

**Pull request closed without merging**
