### PR TITLE
French localization

### PR DESCRIPTION
**Pull request by bmichotte**
ping #2797

### CODE REVIEW

**Comment by bmichotte** [comment]
Obviously a WIP

Btw, I can test it, so I let you all that stuff ;)

**Comment by azeier** [comment]
I moved the Strings files to a separate repo: https://github.com/HearthSim/HDT-Localization

Could you create a new PR over there?

**Comment by bmichotte** [comment]
Sure, I'll do it later today !

**Comment by azeier** [comment]
Thanks.

Implemented the required changed to this repo with 453c993. Closing this PR here.

**Pull request closed without merging**
