### PR TITLE
Fixed the unit test for EliteDeck (which is now EliteHeartstone)

### PR DESCRIPTION
**Pull request by isualize**
EliteDeck is now just a portal which allows users to choose between EliteHearthstone and 2 other websites. This fix parses EliteHearthstone properly.

### CODE REVIEW

**Comment by Epix37** [comment]
[Please use tabs for formatting](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md).

**Comment by isualize** [comment]
Ah sorry, those were settings from work. I updated the file.

**Comment by Epix37** [comment]
:+1:

There should not be spaces before the parenthesis at the `foreach`, `if` and `catch` blocks. Fix those, fIxup everything into one commit and we should be gtm.

**Comment by isualize** [comment]
Any tips on how to squash the commits?

**Comment by Epix37** [comment]
You should be able to do `git rebase -i origin/master` (or `HEAD~5`), pick `77338ba` and `fixup` the rest. Then force push to your branch.

**Comment by Epix37** [comment]
fyi: there's still whitespaces after the `if` and `foreach` :P

**Comment by isualize** [comment]
Ive fixed the if and foreach. I cant figure out how to use the visual studio command prompt. I do a "git rebase -i origin/master" and i get this window which gives me the options for pick and fixup, but i dont know how to use this window..

**Comment by Epix37** [comment]
You need to change `pick` to `fixup` for all but your first commit, then save and close the window.

**Pull request closed without merging**
