### PR TITLE
Filter indicator for issue #3248

### LINKED ISSUE #3248: Add clear indicator that stats are being filtered

### PR DESCRIPTION
**Pull request by Doomfires**
- [x] I have read the [Contributing Guidelines](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md#contributing)
- [x] I have already signed the CLA 

Closes #3248.

### CODE REVIEW

**Comment by riQQ** [comment]
I'll check it out on the weekend.

**Comment by riQQ** [comment]
Imo the notice doesn't stand out enough. And I think placing it as a status bar at the top or the bottom may be better.

Also, when it's loading up with saved filters, the filter indicator incorrectly shows `filters offline`
Current state

**Comment by Doomfires** [comment]
Gotcha! In that case, I'll work on it again when I get back home. I'm
traveling for now, but I'd like to get it fixed up sooner rather than later.

Thanks for the feedback!

**Comment by Jonysegal** [comment]
Closing due to it being three years old.

**Comment by Jonysegal** [comment]
Closing due to it being three years old.

**Pull request closed without merging**
