### PR TITLE
Add custom import for Hearthhead decks

### PR DESCRIPTION
**Pull request by danblair**
Hearthhead no longer supplies meta tags for deck import. This change would use the Hearthhead JSON data that is normally loaded into the windows space of the browser to discover the deck name and deck string for import.

### CODE REVIEW

**Comment by azeier** [comment]
[We no longer want to maintain custom importers](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Web-importing#legacy-support).

This is something they should fix on their end.

As a workaround: You can use their copy deck button for importing decks to HDT.

**Comment by danblair** [comment]
I can certainly agree with not creating a brittle import.  What about removing the Hearthhead unit test then?

**Comment by edzam** [comment]
Looks like I when I migrated Hearthhead to our new framework some things got missed.  This is one of them.  Ill get this ASAP.

**Comment by judge2020** [comment]
@edzam if you'd like, the meta tags were upgraded to where it needs just the deck string over the individual cards https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/RFC-Importing-Implementation.

**Comment by azeier** [comment]
Thanks @edzam :).

The test now works again - might as well keep it. The "Web" tests are not run by CI anyway.

**Pull request closed without merging**
