### PR TITLE
Set explicit AppUserModelID

### LINKED ISSUE #3666: When HDT gets App Update it forgets it has a shortcut in taskbar.
When you pin HDT to taskbar in Windows 10, and launch it from there, App can be accessed by clicking that shortcut.
But if HDT gets updated & you launch it from taskbar with old shortcut, it shows HDT as new app & shows it in different temporary shortcut & clutters space in taskbar.
With every update it gets annoying to unpin old one & repin new shortcut.

### Expected Behavior
When launching updated app, HDT must be accessed via old pinned shortcut.

### Actual Behavior
When launching updated app, HDT is shown in different pinned shortcut (not the one you clicked).

### Steps to reproduce behavior
Pin the HDT to taskbar, wait for app to be updated, launch shortcut from taskbar.

### PR DESCRIPTION
**Pull request by riQQ**
Fixes #3666

- [X] I have read the [Contributing Guidelines](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md#contributing)
- [X] I have already signed the CLA

### CODE REVIEW

**Comment by azeier** [comment]
That's awesome, thanks! Do you know whether this works with squirrel version HDT is currently using?

**Comment by riQQ** [comment]
We are using squirrel 1.7.8 and the guy in the linked issue over at the squirrel repository was using 1.7.7 and this fix supposedly resolved it for him.

`SetCurrentProcessExplicitAppUserModelID` is a Win-API function that is independent of squirrel. So setting any static AppUserModelID without any regard for squirrel should make manually created pins work between different version of the application.

Squirrel creates the pinned entry with a AppUserModelID following the pattern `com.squirrel.{PackageName}.{ExeName}`. So if we use this pattern, pins created by squirrel should also work between different versions.

**Comment by azeier** [comment]
Great! Thanks for the fix.

**Comment by riQQ** [comment]
There are multi places where one has to set an explicit AppUserModelID: https://docs.microsoft.com/de-de/windows/win32/shell/appids#where-to-assign-an-appusermodelid

- Squirrel handle setting the AppUserModelID for shortcuts
- HDT sets the AppUserModelID for the process

**Pull request merged**
