### PR TITLE
fix: always show Tavern Tier 7 setting disabled when Tier7 disabled

### PR DESCRIPTION
**Pull request by DangerousCactus**
- [X] I have read the [Contributing Guidelines](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md#contributing)
- [x] I have already signed the CLA

### CODE REVIEW

**Comment by beheh** [comment]
Hi there, thanks for your PR! All contributions to HearthSim require a signed CLA. I've sent you an [invite](https://github.com/HearthSim/cla/invitations) to [the repository](https://github.com/HearthSim/cla), please follow the instructions there. If you've already signed the CLA, please let us know.

Once that's done and the CLA has been merged, we'll try to get this merged here as soon as possible.

:facepalm: Thanks!

**Comment by beheh** [comment]
:facepalm: Thanks!

**Comment by DangerousCactus** [comment]
Sorry, I'm unable to fork the CLA repository. It says "forking is disabled".

**Comment by beheh** [comment]
Sorry about that, fixed!

**Comment by beheh** [comment]
Thanks!

**Pull request merged**
