### PR TITLE
Mapped SpellSchool to HDT/Card.cs from hearthbCard

### PR DESCRIPTION
**Pull request by slicedbread**
- [x] I have read the [Contributing Guidelines](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CONTRIBUTING.md#contributing)
- [x] I have already signed the CLA 

This PR adds spell schools to Card.cs for use in a multicaster plugin

### CODE REVIEW

**Comment by azeier** [comment]
Can you make that a pass-through prop instead? Like e.g. `Card.CardSet` or `Card.TechLevel`. No need for all the constructor changes. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Hearthstone/Card.cs#L233-L243

**Comment by beheh** [comment]
CLA has been signed.

**Comment by slicedbread** [comment]
> Can you make that a pass-through prop instead? Like e.g. `Card.CardSet` or `Card.TechLevel`. No need for all the constructor changes. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Hearthstone/Card.cs#L233-L243

updated, this is definitely cleaner, thanks for the suggestion

**Comment by azeier** [comment]
👍🏻 Looks good

**Pull request merged**
